# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Tcandy' do

pod "SDWebImage",''
pod 'AFNetworking', '~> 3.0'
pod "MJExtension"
pod "MJRefresh"
pod 'Masonry'
pod 'SDCycleScrollView','~> 1.75'
pod 'ReactiveCocoa', '~> 2.5'
pod 'IQKeyboardManager'


end
